
import StyledComponentsRegistry from "@/lib/registry";
import {GlobalStyles} from "@/app/globals";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    link: "https://use.typekit.net/ptz3vfb.css",
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <GlobalStyles/>
        <StyledComponentsRegistry>
            {children}
        </StyledComponentsRegistry>
        </body>
        </html>
    )
}
