import 'sanitize.css';
import 'sanitize.css/forms.css';
import 'sanitize.css/typography.css';
import StyledComponentsRegistry from "@/lib/registry";
import {GlobalStyles} from "@/styles/globals";
import BackgroundVideo from "@/components/background/background";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    link: "https://use.typekit.net/ptz3vfb.css",
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <StyledComponentsRegistry>
            <GlobalStyles/>
            <BackgroundVideo/>
            {children}
        </StyledComponentsRegistry>
        </body>
        </html>
    )
}
