import 'sanitize.css';
import 'sanitize.css/forms.css';
import 'sanitize.css/typography.css';
import StyledComponentsRegistry from "@/lib/registry";
import {GlobalStyles} from "@/styles/globals";
import {RootLayoutBody} from "@/app/root-layout-body";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    link: "https://use.typekit.net/ptz3vfb.css",
    meta: {name: "viewport", content: "width=device-width, initial-scale=1"},
    script: "particles.js",
}


export default function RootLayout({children}) {
    return (
        <html lang="en">
        <RootLayoutBody>
            <StyledComponentsRegistry>
                <GlobalStyles/>
                {/*<BackgroundVideo/>*/}
                {/*<NavMenu/>*/}
                {children}
            </StyledComponentsRegistry>
        </RootLayoutBody>
        </html>
    )
}
